version: "3.5"
services:
  
  php:
    build: ./docker/php
    container_name: fib-ex-php
    image: fib-ex-php
    networks:
    - network-fib
    environment:
      FIB_ENV: development
    volumes:
      - ".:/project"
      - "$HOME/factorio:/factorio"

networks:
  network-fib:
    name: network-fib
