FactorioItemBrowser\Export\Entity\Dump\Layer:
  exclusion_policy: all
  properties:
    file:
      type: string
    size:
      type: integer
    scale:
      type: float
    shiftX:
      type: integer
    shiftY:
      type: integer
    tintRed:
      type: float
    tintGreen:
      type: float
    tintBlue:
      type: float
    tintAlpha:
      type: float
