FactorioItemBrowser\Export\Entity\Dump\Recipe:
  exclusion_policy: all
  properties:
    name:
      type: string
    localisedName:
      type: raw
    localisedDescription:
      type: raw
    craftingTime:
      type: float
    craftingCategory:
      type: string
    ingredients:
      type: array<FactorioItemBrowser\Export\Entity\Dump\Ingredient>
    products:
      type: array<FactorioItemBrowser\Export\Entity\Dump\Product>
