FactorioItemBrowser\Export\Entity\Dump\Fluid:
  access_type: public_method
  exclusion_policy: all
  properties:
    name:
      type: string
    localisedName:
      type: raw
    localisedDescription:
      type: raw
