FactorioItemBrowser\Export\Entity\InfoJson:
  access_type: public_method
  exclusion_policy: all
  properties:
    name:
      type: string
    title:
      type: string
    description:
      type: string
    version:
      type: string
    factorioVersion:
      type: string
    author:
      type: string
    contact:
      type: string
    homepage:
      type: string
    dependencies:
      type: array<string>
