FactorioItemBrowser\Export\Entity\InfoJson:
  exclusion_policy: all
  properties:
    name:
      type: string
    title:
      type: string
    description:
      type: string
    version:
      type: constructor<BluePsyduck\FactorioModPortalClient\Entity\Version>
    factorioVersion:
      type: constructor<BluePsyduck\FactorioModPortalClient\Entity\Version>
    author:
      type: string
    contact:
      type: string
    homepage:
      type: string
    dependencies:
      type: array<constructor<BluePsyduck\FactorioModPortalClient\Entity\Dependency>>
